- name: Ansible Jenkins Playbook
  remote_user: godi
  become: yes
  hosts: TEST
  tasks:
    - name: Install Java
      command: apt install -y default-jre
    - name: Download Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.68/bin/apache-tomcat-9.0.68.tar.gz
        dest: /opt/apachetomcat.tar.gz
    - name: untar Tomcat
      ansible.builtin.unarchive:
        src: /opt/apachetomcat.tar.gz
        dest: /opt/
        remote_src: yes
    - name: Run Tomcat startup script
      command: nohup /opt/apache-tomcat-9.0.68/bin/startup.sh
    - name: Download Artifact
      get_url:
        url: http://34.93.60.168:8081/service/rest/v1/search/assets/download?sort=version&direction=desc&maven.groupId=com.web_demo&maven.artifactId=web_demo&maven.extension=war
        dest: /opt/apache-tomcat-9.0.68/webapps/web-demo.war
